name: Gisto
url: http://gistoapp.com
gisto_build_date: 2014-03-20
download_url: http://download.gistoapp.com
download_url_mirror: http://mirror.gistoapp.com
year: 2014
pygments: true
markdown: kramdown

releases:
 - version: 0.2.4b
 - version: 0.2.3b
 - version: 0.2.2b
 - version: 0.2.1b
 - version: 0.2.0b
 - version: 0.1.3a
 - version: 0.1.2a

navigation:
- text: Home
  url: /
- text: Features
  url: /features/
- text: Documentation
  url: /documentation/
- text: FAQ
  url: /faq/
- text: Downloads
  url: /download/

contributers:
- name: Maayan Glikser
  gravatar: https://secure.gravatar.com/avatar/3a615b34ef2060face8fcd481c6377e1?s=80
  site: www.glikm.com
  twitter_name: MaayanGlikser
  description: Software developer based in Israel
- name: Sasha Khamkov
  gravatar: https://secure.gravatar.com/avatar/7ddad1a9a1c8de452badaf82b6c30c76?s=80
  site: www.sanusart.com
  twitter_name: sanusart
  description: Sasha is web developer