name: Gisto
url: http://gistoapp.com
gisto_build_date: 2014-06-29
download_url: http://download.gistoapp.com
download_url_mirror: http://mirror.gistoapp.com
nightly_url: http://build.gistoapp.com
year: 2015
highlighter: true
markdown: kramdown

gems:
  - jekyll-sitemap

releases:
 - version: 0.2.6b
 - version: 0.2.5b
 - version: 0.2.4b
 - version: 0.2.3b
 - version: 0.2.2b
 - version: 0.2.1b
 - version: 0.2.0b
 - version: 0.1.3a
 - version: 0.1.2a

navigation:
- text: Home
  url: /
- text: Features
  url: /features/
- text: Documentation
  url: /documentation/
- text: FAQ
  url: /faq/
- text: Blog
  url: /blog/
- text: Downloads
  url: /download/

contributers:
- name: Maayan Glikser
  gravatar: https://secure.gravatar.com/avatar/3a615b34ef2060face8fcd481c6377e1?s=80
  site: www.glikm.com
  twitter_name: MaayanGlikser
  description: Software Developer
- name: Sasha Khamkov
  gravatar: https://secure.gravatar.com/avatar/7ddad1a9a1c8de452badaf82b6c30c76?s=80
  site: www.sanusart.com
  twitter_name: sanusart
  description: Web Developer
